[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-sitemap"

# Headers to ensure proper XML content type for sitemap
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"

# Static page rules with proper server-side rendering
[[redirects]]
  from = "/kaspa/*"
  to = "/.netlify/functions/server-render"
  status = 200
  force = true

# Fallback for other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to ensure proper indexing
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "all"
    Cache-Control = "public, max-age=0, must-revalidate"